import Navbar from "@/components/layout/navbar/Navbar";
import { cn } from "@/utils";
import type { Metadata } from "next";
import { Geist, Italianno } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const italiannoCursive = Italianno({
  variable: "--font-italianno-cursive",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Bella Vista",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(geistSans.variable, italiannoCursive.variable)}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
